### ISSUE TITLE
Rom link incorrect

### ISSUE THREAD

**Issue by Latchkey1998** [djdarien/macpi#1]
The new rom link should be https://github.com/macmade/Macintosh-ROMs/blob/main/Quadra-650.ROM

**Comment by nexusle** [comment]
Also not correct. It must be:

https://github.com/macmade/Macintosh-ROMs/raw/main/Quadra-650.ROM

Also the link for the HDD-script should be:

https://github.com/djdarien/macpi/raw/main/mkmacdisk.sh

**Comment by djdarien** [comment]
@nexusle   Much appreciated on those catches , fixed the readme.md & updated the github pages site . Also created new automated installer with said fixes , enjoy ! https://github.com/djdarien/macpi/blob/e7ad28e4cd051ea2ccb9b808f0b3936a53400124/macpi_auto_installer.sh
